{% set name = "fixtures" %}
{% set version = "3.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "sha256" %}
{% set hash_val = "fcf0d60234f1544da717a9738325812de1f42c2fa085e2d9252d8fff5712b2ef" %}
{% set build = 1 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash }}: {{ hash_val }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pbr >=0.11

  run:
    - python
    - extras
    - pbr >=0.11
    - six
    - testtools >=0.9.22

test:
  imports:
    - fixtures
    - fixtures.callmany
    - fixtures.fixture
    - fixtures.testcase

about:
  home: https://github.com/testing-cabal/fixtures
  license_file: COPYING
  license: Apache 2.0 or BSD 3-Clause
  summary: 'Fixtures, reusable state for writing clean tests and more.'
  dev_url: https://github.com/testing-cabal/fixtures

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
